abilities = {
    "souleater": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 737, "top": 872, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 775, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 812, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 754, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 3200,
            "cast": False,
            "castTime": None,
            "position": {"left": 792, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": False,
            "cast": False,
            "castTime": None,
            "position": {"left": 830, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 870, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 690, "top": 894, "width": 19, "height": 11},
            "directional": False,
            "shortCast": False
        },
    ],
    "summoner": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 2000,
            "position": {"left": 737, "top": 872, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 2000,
            "position": {"left": 775, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 750,
            "cast": False,
            "castTime": None,
            "position": {"left": 812, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1000,
            "position": {"left": 754, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 792, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": False,
            "cast": False,
            "castTime": None,
            "position": {"left": 830, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 870, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1500,
            "position": {"left": 690, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": False
        },
    ],
    "artist": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 737, "top": 872, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 775, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 812, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 754, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 792, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": False,
            "cast": True,
            "castTime": 1000,
            "position": {"left": 830, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 2000,
            "cast": False,
            "castTime": None,
            "position": {"left": 870, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 690, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": False
        },
    ],
    "aero": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 737, "top": 872, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 775, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 812, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 754, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1200,
            "cast": False,
            "castTime": None,
            "position": {"left": 792, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 830, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 870, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 690, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": True
        },
    ],
    "gunslinger": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 2200,
            "cast": False,
            "castTime": None,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 2200,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1200,
            "cast": False,
            "castTime": None,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 2200,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 2200,
            "cast": False,
            "castTime": None,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": False
        },
    ],
    "gunlancer": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1000,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1000,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1500,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 3000,
            "cast": False,
            "castTime": None,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 3000,
            "cast": False,
            "castTime": None,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1500,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": False
        },
    ],
    "arty": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1500,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1900,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 500,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1900,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 300,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": False
        },
    ],
    "sorceress": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1000,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 500,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 500,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 500,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 2000,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 500,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": False,
            "shortCast": False
        },
    ],
    "arcana": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 3000,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1500,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 200,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": False
        },
    ],
    "spear": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 733, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 775, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 812, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1500,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 754, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 2500,
            "cast": False,
            "castTime": None,
            "position": {"left": 792, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 830, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1500,
            "cast": False,
            "castTime": None,
            "position": {"left": 870, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": True,
            "holdTime": 2000,
            "cast": False,
            "castTime": None,
            "position": {"left": 690, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": False
        },
    ],    
    "destroyer": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 4900,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 500,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": True,
            "holdTime": 4000,
            "cast": False,
            "castTime": None,
            "position": {"left": 690, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": False
        },
    ],
    "deathblade": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1500,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 2000,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1500,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "castTime": None,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": False
        },
    ],
    "berserker": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1200,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1500,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1500,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 3500,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1300,
            "cast": False,
            "castTime": None,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1500,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1000,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": False
        },
    ],
    "scrapper": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1500,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True, 
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1400,
            "cast": False,
            "castTime": None,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 2500,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1000,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1500,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": False
        },
    ],
    "reaper": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": False
        },
    ],
    "sharpshooter": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 2200,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 1500,
            "cast": False,
            "castTime": None,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": True,
            "holdTime": 3000,
            "cast": False,
            "castTime": None,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": False
        },
    ],
    "scouter": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1500,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1000,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1500,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": True
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1500,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": True
        },
    ],
    "bard": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "staticImage": True,
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "f",
            "staticImage": True,
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 2500,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": True
        },
{
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "w",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "r",
            "staticImage": True,
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "a",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "s",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "d",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": True,
            "shortCast": False
        },
        {
            "key": "f",
            "staticImage": True,
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": False,
            "shortCast": False
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 2500,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": True,
            "shortCast": True
        },
    ]
}
